// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AlertFrequency.
const (
	AlertFrequencyDaily        AlertFrequency = "daily"
	AlertFrequencyMonthly      AlertFrequency = "monthly"
	AlertFrequencyScheduledRun AlertFrequency = "scheduled_run"
	AlertFrequencyWeekly       AlertFrequency = "weekly"
)

// Valid indicates whether the value is a known member of the AlertFrequency enum.
func (e AlertFrequency) Valid() bool {
	switch e {
	case AlertFrequencyDaily:
		return true
	case AlertFrequencyMonthly:
		return true
	case AlertFrequencyScheduledRun:
		return true
	case AlertFrequencyWeekly:
		return true
	default:
		return false
	}
}

// Defines values for HoldingsImpactPeriodPeriod.
const (
	HoldingsImpactPeriodPeriodInception HoldingsImpactPeriodPeriod = "inception"
	HoldingsImpactPeriodPeriodN1y       HoldingsImpactPeriodPeriod = "1y"
	HoldingsImpactPeriodPeriodN3y       HoldingsImpactPeriodPeriod = "3y"
	HoldingsImpactPeriodPeriodN5y       HoldingsImpactPeriodPeriod = "5y"
	HoldingsImpactPeriodPeriodYtd       HoldingsImpactPeriodPeriod = "ytd"
)

// Valid indicates whether the value is a known member of the HoldingsImpactPeriodPeriod enum.
func (e HoldingsImpactPeriodPeriod) Valid() bool {
	switch e {
	case HoldingsImpactPeriodPeriodInception:
		return true
	case HoldingsImpactPeriodPeriodN1y:
		return true
	case HoldingsImpactPeriodPeriodN3y:
		return true
	case HoldingsImpactPeriodPeriodN5y:
		return true
	case HoldingsImpactPeriodPeriodYtd:
		return true
	default:
		return false
	}
}

// Defines values for MetricFormat.
const (
	Number  MetricFormat = "number"
	Percent MetricFormat = "percent"
)

// Valid indicates whether the value is a known member of the MetricFormat enum.
func (e MetricFormat) Valid() bool {
	switch e {
	case Number:
		return true
	case Percent:
		return true
	default:
		return false
	}
}

// Defines values for PortfolioPerformanceResolution.
const (
	PortfolioPerformanceResolutionDaily   PortfolioPerformanceResolution = "daily"
	PortfolioPerformanceResolutionMonthly PortfolioPerformanceResolution = "monthly"
	PortfolioPerformanceResolutionWeekly  PortfolioPerformanceResolution = "weekly"
)

// Valid indicates whether the value is a known member of the PortfolioPerformanceResolution enum.
func (e PortfolioPerformanceResolution) Valid() bool {
	switch e {
	case PortfolioPerformanceResolutionDaily:
		return true
	case PortfolioPerformanceResolutionMonthly:
		return true
	case PortfolioPerformanceResolutionWeekly:
		return true
	default:
		return false
	}
}

// Defines values for PortfolioStatus.
const (
	PortfolioStatusFailed  PortfolioStatus = "failed"
	PortfolioStatusPending PortfolioStatus = "pending"
	PortfolioStatusReady   PortfolioStatus = "ready"
	PortfolioStatusRunning PortfolioStatus = "running"
)

// Valid indicates whether the value is a known member of the PortfolioStatus enum.
func (e PortfolioStatus) Valid() bool {
	switch e {
	case PortfolioStatusFailed:
		return true
	case PortfolioStatusPending:
		return true
	case PortfolioStatusReady:
		return true
	case PortfolioStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for ReturnRowKind.
const (
	ReturnRowKindBenchmark    ReturnRowKind = "benchmark"
	ReturnRowKindBenchmarkTax ReturnRowKind = "benchmark-tax"
	ReturnRowKindPortfolio    ReturnRowKind = "portfolio"
	ReturnRowKindPortfolioTax ReturnRowKind = "portfolio-tax"
)

// Valid indicates whether the value is a known member of the ReturnRowKind enum.
func (e ReturnRowKind) Valid() bool {
	switch e {
	case ReturnRowKindBenchmark:
		return true
	case ReturnRowKindBenchmarkTax:
		return true
	case ReturnRowKindPortfolio:
		return true
	case ReturnRowKindPortfolioTax:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusFailed  RunStatus = "failed"
	RunStatusQueued  RunStatus = "queued"
	RunStatusRunning RunStatus = "running"
	RunStatusSuccess RunStatus = "success"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusFailed:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for StrategyInstallState.
const (
	Failed     StrategyInstallState = "failed"
	Installing StrategyInstallState = "installing"
	Pending    StrategyInstallState = "pending"
	Ready      StrategyInstallState = "ready"
)

// Valid indicates whether the value is a known member of the StrategyInstallState enum.
func (e StrategyInstallState) Valid() bool {
	switch e {
	case Failed:
		return true
	case Installing:
		return true
	case Pending:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for TransactionType.
const (
	Buy        TransactionType = "buy"
	Deposit    TransactionType = "deposit"
	Dividend   TransactionType = "dividend"
	Fee        TransactionType = "fee"
	Interest   TransactionType = "interest"
	Journal    TransactionType = "journal"
	Sell       TransactionType = "sell"
	Split      TransactionType = "split"
	Withdrawal TransactionType = "withdrawal"
)

// Valid indicates whether the value is a known member of the TransactionType enum.
func (e TransactionType) Valid() bool {
	switch e {
	case Buy:
		return true
	case Deposit:
		return true
	case Dividend:
		return true
	case Fee:
		return true
	case Interest:
		return true
	case Journal:
		return true
	case Sell:
		return true
	case Split:
		return true
	case Withdrawal:
		return true
	default:
		return false
	}
}

// Defines values for GetPortfolioMetricsParamsWindow.
const (
	GetPortfolioMetricsParamsWindowMtd            GetPortfolioMetricsParamsWindow = "mtd"
	GetPortfolioMetricsParamsWindowN1yr           GetPortfolioMetricsParamsWindow = "1yr"
	GetPortfolioMetricsParamsWindowN3yr           GetPortfolioMetricsParamsWindow = "3yr"
	GetPortfolioMetricsParamsWindowN5yr           GetPortfolioMetricsParamsWindow = "5yr"
	GetPortfolioMetricsParamsWindowSinceInception GetPortfolioMetricsParamsWindow = "since_inception"
	GetPortfolioMetricsParamsWindowWtd            GetPortfolioMetricsParamsWindow = "wtd"
	GetPortfolioMetricsParamsWindowYtd            GetPortfolioMetricsParamsWindow = "ytd"
)

// Valid indicates whether the value is a known member of the GetPortfolioMetricsParamsWindow enum.
func (e GetPortfolioMetricsParamsWindow) Valid() bool {
	switch e {
	case GetPortfolioMetricsParamsWindowMtd:
		return true
	case GetPortfolioMetricsParamsWindowN1yr:
		return true
	case GetPortfolioMetricsParamsWindowN3yr:
		return true
	case GetPortfolioMetricsParamsWindowN5yr:
		return true
	case GetPortfolioMetricsParamsWindowSinceInception:
		return true
	case GetPortfolioMetricsParamsWindowWtd:
		return true
	case GetPortfolioMetricsParamsWindowYtd:
		return true
	default:
		return false
	}
}

// Defines values for GetPortfolioMetricsParamsMetric.
const (
	ActiveReturn            GetPortfolioMetricsParamsMetric = "ActiveReturn"
	Alpha                   GetPortfolioMetricsParamsMetric = "Alpha"
	AverageHoldingPeriod    GetPortfolioMetricsParamsMetric = "AverageHoldingPeriod"
	AverageLoss             GetPortfolioMetricsParamsMetric = "AverageLoss"
	AverageMAE              GetPortfolioMetricsParamsMetric = "AverageMAE"
	AverageMFE              GetPortfolioMetricsParamsMetric = "AverageMFE"
	AverageWin              GetPortfolioMetricsParamsMetric = "AverageWin"
	AvgDrawdown             GetPortfolioMetricsParamsMetric = "AvgDrawdown"
	AvgDrawdownDays         GetPortfolioMetricsParamsMetric = "AvgDrawdownDays"
	AvgUlcerIndex           GetPortfolioMetricsParamsMetric = "AvgUlcerIndex"
	Beta                    GetPortfolioMetricsParamsMetric = "Beta"
	CAGR                    GetPortfolioMetricsParamsMetric = "CAGR"
	CVaR                    GetPortfolioMetricsParamsMetric = "CVaR"
	Calmar                  GetPortfolioMetricsParamsMetric = "Calmar"
	ConsecutiveLosses       GetPortfolioMetricsParamsMetric = "ConsecutiveLosses"
	ConsecutiveWins         GetPortfolioMetricsParamsMetric = "ConsecutiveWins"
	DownsideCaptureRatio    GetPortfolioMetricsParamsMetric = "DownsideCaptureRatio"
	DownsideDeviation       GetPortfolioMetricsParamsMetric = "DownsideDeviation"
	DynamicWithdrawalRate   GetPortfolioMetricsParamsMetric = "DynamicWithdrawalRate"
	EdgeRatio               GetPortfolioMetricsParamsMetric = "EdgeRatio"
	ExcessKurtosis          GetPortfolioMetricsParamsMetric = "ExcessKurtosis"
	Exposure                GetPortfolioMetricsParamsMetric = "Exposure"
	GainLossRatio           GetPortfolioMetricsParamsMetric = "GainLossRatio"
	GainToPainRatio         GetPortfolioMetricsParamsMetric = "GainToPainRatio"
	InformationRatio        GetPortfolioMetricsParamsMetric = "InformationRatio"
	KRatio                  GetPortfolioMetricsParamsMetric = "KRatio"
	KellerRatio             GetPortfolioMetricsParamsMetric = "KellerRatio"
	KellyCriterion          GetPortfolioMetricsParamsMetric = "KellyCriterion"
	LTCG                    GetPortfolioMetricsParamsMetric = "LTCG"
	LongProfitFactor        GetPortfolioMetricsParamsMetric = "LongProfitFactor"
	LongWinRate             GetPortfolioMetricsParamsMetric = "LongWinRate"
	MWRR                    GetPortfolioMetricsParamsMetric = "MWRR"
	MaxDrawdown             GetPortfolioMetricsParamsMetric = "MaxDrawdown"
	MedianMAE               GetPortfolioMetricsParamsMetric = "MedianMAE"
	MedianMFE               GetPortfolioMetricsParamsMetric = "MedianMFE"
	MedianUlcerIndex        GetPortfolioMetricsParamsMetric = "MedianUlcerIndex"
	NPositivePeriods        GetPortfolioMetricsParamsMetric = "NPositivePeriods"
	NonQualifiedIncome      GetPortfolioMetricsParamsMetric = "NonQualifiedIncome"
	OmegaRatio              GetPortfolioMetricsParamsMetric = "OmegaRatio"
	P90UlcerIndex           GetPortfolioMetricsParamsMetric = "P90UlcerIndex"
	PerpetualWithdrawalRate GetPortfolioMetricsParamsMetric = "PerpetualWithdrawalRate"
	ProbabilisticSharpe     GetPortfolioMetricsParamsMetric = "ProbabilisticSharpe"
	ProfitFactor            GetPortfolioMetricsParamsMetric = "ProfitFactor"
	QualifiedDividends      GetPortfolioMetricsParamsMetric = "QualifiedDividends"
	RSquared                GetPortfolioMetricsParamsMetric = "RSquared"
	RecoveryFactor          GetPortfolioMetricsParamsMetric = "RecoveryFactor"
	STCG                    GetPortfolioMetricsParamsMetric = "STCG"
	SafeWithdrawalRate      GetPortfolioMetricsParamsMetric = "SafeWithdrawalRate"
	Sharpe                  GetPortfolioMetricsParamsMetric = "Sharpe"
	ShortProfitFactor       GetPortfolioMetricsParamsMetric = "ShortProfitFactor"
	ShortWinRate            GetPortfolioMetricsParamsMetric = "ShortWinRate"
	Skewness                GetPortfolioMetricsParamsMetric = "Skewness"
	SmartSharpe             GetPortfolioMetricsParamsMetric = "SmartSharpe"
	SmartSortino            GetPortfolioMetricsParamsMetric = "SmartSortino"
	Sortino                 GetPortfolioMetricsParamsMetric = "Sortino"
	StdDev                  GetPortfolioMetricsParamsMetric = "StdDev"
	TWRR                    GetPortfolioMetricsParamsMetric = "TWRR"
	TailRatio               GetPortfolioMetricsParamsMetric = "TailRatio"
	TaxCostRatio            GetPortfolioMetricsParamsMetric = "TaxCostRatio"
	TaxDrag                 GetPortfolioMetricsParamsMetric = "TaxDrag"
	TrackingError           GetPortfolioMetricsParamsMetric = "TrackingError"
	TradeCaptureRatio       GetPortfolioMetricsParamsMetric = "TradeCaptureRatio"
	TradeGainLossRatio      GetPortfolioMetricsParamsMetric = "TradeGainLossRatio"
	Treynor                 GetPortfolioMetricsParamsMetric = "Treynor"
	Turnover                GetPortfolioMetricsParamsMetric = "Turnover"
	UlcerIndex              GetPortfolioMetricsParamsMetric = "UlcerIndex"
	UnrealizedLTCG          GetPortfolioMetricsParamsMetric = "UnrealizedLTCG"
	UnrealizedSTCG          GetPortfolioMetricsParamsMetric = "UnrealizedSTCG"
	UpsideCaptureRatio      GetPortfolioMetricsParamsMetric = "UpsideCaptureRatio"
	ValueAtRisk             GetPortfolioMetricsParamsMetric = "ValueAtRisk"
	WinRate                 GetPortfolioMetricsParamsMetric = "WinRate"
)

// Valid indicates whether the value is a known member of the GetPortfolioMetricsParamsMetric enum.
func (e GetPortfolioMetricsParamsMetric) Valid() bool {
	switch e {
	case ActiveReturn:
		return true
	case Alpha:
		return true
	case AverageHoldingPeriod:
		return true
	case AverageLoss:
		return true
	case AverageMAE:
		return true
	case AverageMFE:
		return true
	case AverageWin:
		return true
	case AvgDrawdown:
		return true
	case AvgDrawdownDays:
		return true
	case AvgUlcerIndex:
		return true
	case Beta:
		return true
	case CAGR:
		return true
	case CVaR:
		return true
	case Calmar:
		return true
	case ConsecutiveLosses:
		return true
	case ConsecutiveWins:
		return true
	case DownsideCaptureRatio:
		return true
	case DownsideDeviation:
		return true
	case DynamicWithdrawalRate:
		return true
	case EdgeRatio:
		return true
	case ExcessKurtosis:
		return true
	case Exposure:
		return true
	case GainLossRatio:
		return true
	case GainToPainRatio:
		return true
	case InformationRatio:
		return true
	case KRatio:
		return true
	case KellerRatio:
		return true
	case KellyCriterion:
		return true
	case LTCG:
		return true
	case LongProfitFactor:
		return true
	case LongWinRate:
		return true
	case MWRR:
		return true
	case MaxDrawdown:
		return true
	case MedianMAE:
		return true
	case MedianMFE:
		return true
	case MedianUlcerIndex:
		return true
	case NPositivePeriods:
		return true
	case NonQualifiedIncome:
		return true
	case OmegaRatio:
		return true
	case P90UlcerIndex:
		return true
	case PerpetualWithdrawalRate:
		return true
	case ProbabilisticSharpe:
		return true
	case ProfitFactor:
		return true
	case QualifiedDividends:
		return true
	case RSquared:
		return true
	case RecoveryFactor:
		return true
	case STCG:
		return true
	case SafeWithdrawalRate:
		return true
	case Sharpe:
		return true
	case ShortProfitFactor:
		return true
	case ShortWinRate:
		return true
	case Skewness:
		return true
	case SmartSharpe:
		return true
	case SmartSortino:
		return true
	case Sortino:
		return true
	case StdDev:
		return true
	case TWRR:
		return true
	case TailRatio:
		return true
	case TaxCostRatio:
		return true
	case TaxDrag:
		return true
	case TrackingError:
		return true
	case TradeCaptureRatio:
		return true
	case TradeGainLossRatio:
		return true
	case Treynor:
		return true
	case Turnover:
		return true
	case UlcerIndex:
		return true
	case UnrealizedLTCG:
		return true
	case UnrealizedSTCG:
		return true
	case UpsideCaptureRatio:
		return true
	case ValueAtRisk:
		return true
	case WinRate:
		return true
	default:
		return false
	}
}

// Defines values for GetPortfolioPerformanceParamsResolution.
const (
	Daily   GetPortfolioPerformanceParamsResolution = "daily"
	Monthly GetPortfolioPerformanceParamsResolution = "monthly"
	Weekly  GetPortfolioPerformanceParamsResolution = "weekly"
)

// Valid indicates whether the value is a known member of the GetPortfolioPerformanceParamsResolution enum.
func (e GetPortfolioPerformanceParamsResolution) Valid() bool {
	switch e {
	case Daily:
		return true
	case Monthly:
		return true
	case Weekly:
		return true
	default:
		return false
	}
}

// Alert defines model for Alert.
type Alert struct {
	// Frequency How often the alert fires. `scheduled_run` fires on every completed backtest run; the others fire on calendar cadence.
	Frequency   AlertFrequency     `json:"frequency"`
	Id          openapi_types.UUID `json:"id"`
	LastSentAt  *time.Time         `json:"lastSentAt,omitempty"`
	PortfolioId openapi_types.UUID `json:"portfolioId"`

	// Recipients Email addresses that receive the alert.
	Recipients []string `json:"recipients"`
}

// AlertCreateRequest defines model for AlertCreateRequest.
type AlertCreateRequest struct {
	// Frequency How often the alert fires. `scheduled_run` fires on every completed backtest run; the others fire on calendar cadence.
	Frequency AlertFrequency `json:"frequency"`

	// Recipients At least one recipient required.
	Recipients []string `json:"recipients"`
}

// AlertFrequency How often the alert fires. `scheduled_run` fires on every completed backtest run; the others fire on calendar cadence.
type AlertFrequency string

// AlertUpdateRequest All fields optional; omit any field you do not want to change.
type AlertUpdateRequest struct {
	// Frequency How often the alert fires. `scheduled_run` fires on every completed backtest run; the others fire on calendar cadence.
	Frequency  *AlertFrequency `json:"frequency,omitempty"`
	Recipients *[]string       `json:"recipients,omitempty"`
}

// BacktestRun defines model for BacktestRun.
type BacktestRun struct {
	DurationMs    *int               `json:"durationMs,omitempty"`
	Error         *string            `json:"error,omitempty"`
	FinishedAt    *time.Time         `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	PortfolioSlug string             `json:"portfolioSlug"`
	StartedAt     *time.Time         `json:"startedAt,omitempty"`
	Status        RunStatus          `json:"status"`
}

// Drawdown defines model for Drawdown.
type Drawdown struct {
	// Days Trading days from start to recovery (or end of series if unrecovered).
	Days *int `json:"days,omitempty"`

	// Depth Decimal percent, negative (e.g. -0.1670 = −16.70%).
	Depth float64 `json:"depth"`

	// Recovery Date equity returned to the prior peak. Null if unrecovered.
	Recovery *openapi_types.Date `json:"recovery,omitempty"`

	// Start Peak date when the drawdown began.
	Start openapi_types.Date `json:"start"`

	// Trough Date of the deepest point.
	Trough openapi_types.Date `json:"trough"`
}

// HistoricalHolding Position reconstructed by replaying transactions. lastTradeValue is
// quantity × last trade price seen in the transaction log, not a
// mark-to-market value from a pricing feed.
type HistoricalHolding struct {
	AvgCost        float64 `json:"avgCost"`
	Figi           *string `json:"figi,omitempty"`
	LastTradeValue float64 `json:"lastTradeValue"`
	Quantity       float64 `json:"quantity"`
	Ticker         string  `json:"ticker"`
}

// Holding defines model for Holding.
type Holding struct {
	AvgCost float64 `json:"avgCost"`

	// DayChange Decimal percent since previous close.
	DayChange   *float64 `json:"dayChange,omitempty"`
	Figi        *string  `json:"figi,omitempty"`
	MarketValue float64  `json:"marketValue"`
	Quantity    float64  `json:"quantity"`
	Ticker      string   `json:"ticker"`
}

// HoldingsAsOfResponse defines model for HoldingsAsOfResponse.
type HoldingsAsOfResponse struct {
	Date                openapi_types.Date  `json:"date"`
	Items               []HistoricalHolding `json:"items"`
	TotalLastTradeValue float64             `json:"totalLastTradeValue"`
}

// HoldingsHistoryEntry defines model for HoldingsHistoryEntry.
type HoldingsHistoryEntry struct {
	// Annotations Optional strategy-written key/value labels for this batch.
	Annotations *map[string]string  `json:"annotations,omitempty"`
	BatchId     int64               `json:"batchId"`
	Items       []HistoricalHolding `json:"items"`

	// PortfolioValue Authoritative mark-to-market portfolio total on the batch's date,
	// read from perf_data. Null when no perf_data row exists for that
	// date (e.g. batch timestamp falls outside the equity curve).
	PortfolioValue *float64  `json:"portfolioValue,omitempty"`
	Timestamp      time.Time `json:"timestamp"`
}

// HoldingsHistoryResponse defines model for HoldingsHistoryResponse.
type HoldingsHistoryResponse struct {
	Items []HoldingsHistoryEntry `json:"items"`
}

// HoldingsImpactItem defines model for HoldingsImpactItem.
type HoldingsImpactItem struct {
	AvgWeight    float64 `json:"avgWeight"`
	Contribution float64 `json:"contribution"`

	// Figi Composite FIGI. Empty string for synthetic tickers like $CASH.
	Figi        *string `json:"figi,omitempty"`
	HoldingDays int64   `json:"holdingDays"`
	Ticker      string  `json:"ticker"`
}

// HoldingsImpactPeriod defines model for HoldingsImpactPeriod.
type HoldingsImpactPeriod struct {
	AnnualizedReturn float64                    `json:"annualizedReturn"`
	CumulativeReturn float64                    `json:"cumulativeReturn"`
	EndDate          openapi_types.Date         `json:"endDate"`
	Items            []HoldingsImpactItem       `json:"items"`
	Label            string                     `json:"label"`
	Period           HoldingsImpactPeriodPeriod `json:"period"`
	Rest             HoldingsImpactRest         `json:"rest"`
	StartDate        openapi_types.Date         `json:"startDate"`
	Years            float64                    `json:"years"`
}

// HoldingsImpactPeriodPeriod defines model for HoldingsImpactPeriod.Period.
type HoldingsImpactPeriodPeriod string

// HoldingsImpactResponse defines model for HoldingsImpactResponse.
type HoldingsImpactResponse struct {
	AsOf openapi_types.Date `json:"asOf"`

	// Currency ISO 4217 currency code of the portfolio's reporting currency.
	Currency      string                 `json:"currency"`
	Periods       []HoldingsImpactPeriod `json:"periods"`
	PortfolioSlug string                 `json:"portfolioSlug"`
}

// HoldingsImpactRest defines model for HoldingsImpactRest.
type HoldingsImpactRest struct {
	Contribution float64 `json:"contribution"`
	Count        int64   `json:"count"`
}

// HoldingsResponse defines model for HoldingsResponse.
type HoldingsResponse struct {
	Date             openapi_types.Date `json:"date"`
	Items            []Holding          `json:"items"`
	TotalMarketValue float64            `json:"totalMarketValue"`
}

// MetricFormat How the value should be rendered. Percent values are decimal (0.1147 = 11.47%).
type MetricFormat string

// MetricGroup Map of pvbt metric name to array of values, one per requested window.
type MetricGroup map[string][]*float64

// PerformancePoint defines model for PerformancePoint.
type PerformancePoint struct {
	// BenchmarkValue Normalized to start at the portfolio's opening value.
	BenchmarkValue float64            `json:"benchmarkValue"`
	Date           openapi_types.Date `json:"date"`
	PortfolioValue float64            `json:"portfolioValue"`

	// RiskFreeRate Annualized risk-free rate at this date (e.g. 3-month T-Bill). Optional.
	RiskFreeRate *float64 `json:"riskFreeRate,omitempty"`
}

// Portfolio Portfolio configuration. Derived backtest output lives on separate endpoints.
type Portfolio struct {
	Benchmark string    `json:"benchmark"`
	CreatedAt time.Time `json:"createdAt"`

	// EndDate Backtest end date (YYYY-MM-DD). Absent or null means today.
	EndDate    *openapi_types.Date    `json:"endDate,omitempty"`
	LastError  *string                `json:"lastError,omitempty"`
	LastRunAt  *time.Time             `json:"lastRunAt,omitempty"`
	Name       string                 `json:"name"`
	Parameters map[string]interface{} `json:"parameters"`

	// PresetName Name of the matched strategy preset, or null when parameters did not match a preset.
	PresetName *string `json:"presetName,omitempty"`
	Slug       string  `json:"slug"`

	// StartDate Backtest start date (YYYY-MM-DD). Absent or null means strategy default.
	StartDate *openapi_types.Date `json:"startDate,omitempty"`

	// Status Current lifecycle status of the portfolio's backtest.
	Status PortfolioStatus `json:"status"`

	// StrategyCloneUrl Clone URL for unofficial strategies; empty string for official ones.
	StrategyCloneUrl *string `json:"strategyCloneUrl,omitempty"`
	StrategyCode     string  `json:"strategyCode"`

	// StrategyVer Pinned strategy version (null for unofficial portfolios).
	StrategyVer *string   `json:"strategyVer,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// PortfolioCreateRequest Exactly one of `strategyCode` or `strategyCloneUrl` must be provided;
// supplying both or neither returns 422. Enforced by the handler, not
// by the JSON schema (oneOf omitted to keep the generated Go type flat).
type PortfolioCreateRequest struct {
	Benchmark *string `json:"benchmark,omitempty"`

	// EndDate Backtest end date (YYYY-MM-DD). Omit to use today.
	EndDate *openapi_types.Date `json:"endDate,omitempty"`

	// Name User-visible display name.
	Name string `json:"name"`

	// Parameters Values validated against the strategy's declared parameters.
	Parameters map[string]interface{} `json:"parameters"`

	// StartDate Backtest start date (YYYY-MM-DD). Omit to use the strategy default.
	StartDate *openapi_types.Date `json:"startDate,omitempty"`

	// StrategyCloneUrl HTTPS GitHub clone URL. Mutually exclusive with strategyCode.
	StrategyCloneUrl *string `json:"strategyCloneUrl,omitempty"`

	// StrategyCode Strategy short code (from `describe` output).
	StrategyCode *string `json:"strategyCode,omitempty"`

	// StrategyVer Specific version to pin; omit for latest installed.
	StrategyVer *string `json:"strategyVer,omitempty"`
}

// PortfolioCreated defines model for PortfolioCreated.
type PortfolioCreated struct {
	Benchmark string    `json:"benchmark"`
	CreatedAt time.Time `json:"createdAt"`

	// EndDate Backtest end date (YYYY-MM-DD). Absent or null means today.
	EndDate    *openapi_types.Date    `json:"endDate,omitempty"`
	LastError  *string                `json:"lastError,omitempty"`
	LastRunAt  *time.Time             `json:"lastRunAt,omitempty"`
	Name       string                 `json:"name"`
	Parameters map[string]interface{} `json:"parameters"`

	// PresetName Name of the matched strategy preset, or null when parameters did not match a preset.
	PresetName *string `json:"presetName,omitempty"`

	// RunId ID of the backtest run automatically queued on creation. Present only when a dispatcher is configured; use with the SSE progress endpoint.
	RunId *openapi_types.UUID `json:"runId,omitempty"`
	Slug  string              `json:"slug"`

	// StartDate Backtest start date (YYYY-MM-DD). Absent or null means strategy default.
	StartDate *openapi_types.Date `json:"startDate,omitempty"`

	// Status Current lifecycle status of the portfolio's backtest.
	Status PortfolioStatus `json:"status"`

	// StrategyCloneUrl Clone URL for unofficial strategies; empty string for official ones.
	StrategyCloneUrl *string `json:"strategyCloneUrl,omitempty"`
	StrategyCode     string  `json:"strategyCode"`

	// StrategyVer Pinned strategy version (null for unofficial portfolios).
	StrategyVer *string   `json:"strategyVer,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// PortfolioMetrics All pvbt metrics grouped by category, column-oriented against a shared windows list.
type PortfolioMetrics struct {
	// Advanced Map of pvbt metric name to array of values, one per requested window.
	Advanced *MetricGroup `json:"advanced,omitempty"`

	// Risk Map of pvbt metric name to array of values, one per requested window.
	Risk *MetricGroup `json:"risk,omitempty"`

	// Summary Map of pvbt metric name to array of values, one per requested window.
	Summary *MetricGroup `json:"summary,omitempty"`

	// Tax Map of pvbt metric name to array of values, one per requested window.
	Tax *MetricGroup `json:"tax,omitempty"`

	// Trade Map of pvbt metric name to array of values, one per requested window.
	Trade *MetricGroup `json:"trade,omitempty"`

	// Windows Ordered list of requested windows. Each metric value array is aligned to this list.
	Windows []string `json:"windows"`

	// Withdrawal Map of pvbt metric name to array of values, one per requested window.
	Withdrawal *MetricGroup `json:"withdrawal,omitempty"`
}

// PortfolioPerformance defines model for PortfolioPerformance.
type PortfolioPerformance struct {
	From          openapi_types.Date              `json:"from"`
	Points        []PerformancePoint              `json:"points"`
	PortfolioSlug string                          `json:"portfolioSlug"`
	Resolution    *PortfolioPerformanceResolution `json:"resolution,omitempty"`
	To            openapi_types.Date              `json:"to"`
}

// PortfolioPerformanceResolution defines model for PortfolioPerformance.Resolution.
type PortfolioPerformanceResolution string

// PortfolioStatistic defines model for PortfolioStatistic.
type PortfolioStatistic struct {
	// Format How the value should be rendered. Percent values are decimal (0.1147 = 11.47%).
	Format MetricFormat `json:"format"`
	Label  string       `json:"label"`
	Value  float64      `json:"value"`
}

// PortfolioStatus Current lifecycle status of the portfolio's backtest.
type PortfolioStatus string

// PortfolioSummary Top-line numbers for the KPI strip.
type PortfolioSummary struct {
	Alpha              float64  `json:"alpha"`
	BenchmarkYtdReturn float64  `json:"benchmarkYtdReturn"`
	Beta               float64  `json:"beta"`
	CagrSinceInception float64  `json:"cagrSinceInception"`
	CurrentValue       float64  `json:"currentValue"`
	MaxDrawDown        float64  `json:"maxDrawDown"`
	OneYearReturn      float64  `json:"oneYearReturn"`
	Sharpe             float64  `json:"sharpe"`
	Sortino            float64  `json:"sortino"`
	StdDev             float64  `json:"stdDev"`
	TaxCostRatio       float64  `json:"taxCostRatio"`
	UlcerIndex         *float64 `json:"ulcerIndex,omitempty"`
	YtdReturn          float64  `json:"ytdReturn"`
}

// PortfolioUpdateRequest PATCH body. Only `name`, `startDate`, and `endDate` are mutable.
// Any other field is rejected with 422. All fields are optional; omit
// any field you do not want to change.
type PortfolioUpdateRequest struct {
	// EndDate Backtest end date (YYYY-MM-DD).
	EndDate *openapi_types.Date `json:"endDate,omitempty"`
	Name    *string             `json:"name,omitempty"`

	// StartDate Backtest start date (YYYY-MM-DD).
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
}

// Problem RFC 7807 Problem Details.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference that identifies the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title Short, human-readable summary.
	Title string `json:"title"`

	// Type URI identifying the problem type.
	Type *string `json:"type,omitempty"`
}

// ReturnRowKind Which line in the trailing returns table.
type ReturnRowKind string

// RunStatus defines model for RunStatus.
type RunStatus string

// Strategy defines model for Strategy.
type Strategy struct {
	Cagr             *float64             `json:"cagr,omitempty"`
	Categories       *[]string            `json:"categories,omitempty"`
	CloneUrl         *string              `json:"cloneUrl,omitempty"`
	Describe         *StrategyDescribe    `json:"describe,omitempty"`
	Description      *string              `json:"description,omitempty"`
	InstallError     *string              `json:"installError,omitempty"`
	InstallState     StrategyInstallState `json:"installState"`
	InstalledAt      *time.Time           `json:"installedAt,omitempty"`
	InstalledVer     *string              `json:"installedVer,omitempty"`
	IsOfficial       bool                 `json:"isOfficial"`
	LastAttemptedVer *string              `json:"lastAttemptedVer,omitempty"`
	MaxDrawDown      *float64             `json:"maxDrawDown,omitempty"`

	// OwnerSub Auth0 sub of the registering user; NULL for official strategies.
	OwnerSub  *string  `json:"ownerSub,omitempty"`
	RepoName  string   `json:"repoName"`
	RepoOwner string   `json:"repoOwner"`
	Sharpe    *float64 `json:"sharpe,omitempty"`
	ShortCode string   `json:"shortCode"`
	Stars     *int     `json:"stars,omitempty"`
}

// StrategyDescribe defines model for StrategyDescribe.
type StrategyDescribe struct {
	Benchmark   string              `json:"benchmark"`
	Description *string             `json:"description,omitempty"`
	Name        string              `json:"name"`
	Parameters  []StrategyParameter `json:"parameters"`
	Presets     *[]StrategyPreset   `json:"presets,omitempty"`
	Schedule    string              `json:"schedule"`
	ShortCode   string              `json:"shortCode"`
}

// StrategyInstallState defines model for StrategyInstallState.
type StrategyInstallState string

// StrategyParameter defines model for StrategyParameter.
type StrategyParameter struct {
	// Default Default value — may be any JSON-serializable type.
	Default     interface{} `json:"default,omitempty"`
	Description *string     `json:"description,omitempty"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
}

// StrategyPreset defines model for StrategyPreset.
type StrategyPreset struct {
	Name       string                 `json:"name"`
	Parameters map[string]interface{} `json:"parameters"`
}

// TrailingReturnRow defines model for TrailingReturnRow.
type TrailingReturnRow struct {
	FiveYear float64 `json:"fiveYear"`

	// Kind Which line in the trailing returns table.
	Kind           ReturnRowKind `json:"kind"`
	OneYear        float64       `json:"oneYear"`
	SinceInception float64       `json:"sinceInception"`
	TenYear        float64       `json:"tenYear"`
	ThreeYear      float64       `json:"threeYear"`
	Title          string        `json:"title"`
	Ytd            float64       `json:"ytd"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount *float64 `json:"amount,omitempty"`

	// BatchId Batch (rebalance event) this transaction belongs to.
	BatchId       int64              `json:"batchId"`
	Date          openapi_types.Date `json:"date"`
	Figi          *string            `json:"figi,omitempty"`
	Justification *string            `json:"justification,omitempty"`
	Price         *float64           `json:"price,omitempty"`
	Qualified     *bool              `json:"qualified,omitempty"`
	Quantity      *float64           `json:"quantity,omitempty"`
	Ticker        *string            `json:"ticker,omitempty"`
	Type          TransactionType    `json:"type"`
}

// TransactionType defines model for Transaction.Type.
type TransactionType string

// TransactionsResponse defines model for TransactionsResponse.
type TransactionsResponse struct {
	Items []Transaction `json:"items"`
}

// PortfolioSlug defines model for PortfolioSlug.
type PortfolioSlug = string

// BadRequest RFC 7807 Problem Details.
type BadRequest = Problem

// Conflict RFC 7807 Problem Details.
type Conflict = Problem

// NotFound RFC 7807 Problem Details.
type NotFound = Problem

// ServerError RFC 7807 Problem Details.
type ServerError = Problem

// Unauthorized RFC 7807 Problem Details.
type Unauthorized = Problem

// UnprocessableEntity RFC 7807 Problem Details.
type UnprocessableEntity = Problem

// GetPortfolioHoldingsImpactParams defines parameters for GetPortfolioHoldingsImpact.
type GetPortfolioHoldingsImpactParams struct {
	// Top Maximum number of named holdings per period (remaining folded into `rest`). Values outside [1, 50] are clamped silently.
	Top *int `form:"top,omitempty" json:"top,omitempty"`
}

// GetPortfolioHoldingsHistoryParams defines parameters for GetPortfolioHoldingsHistory.
type GetPortfolioHoldingsHistoryParams struct {
	// From Inclusive lower bound on batch timestamp (YYYY-MM-DD).
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper bound on batch timestamp (YYYY-MM-DD).
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetPortfolioMetricsParams defines parameters for GetPortfolioMetrics.
type GetPortfolioMetricsParams struct {
	// Window One or more windows to include. Repeatable. Default is since_inception.
	Window *[]GetPortfolioMetricsParamsWindow `form:"window,omitempty" json:"window,omitempty"`

	// Metric One or more pvbt PascalCase metric names to include. Repeatable. Default is all metrics.
	Metric *[]GetPortfolioMetricsParamsMetric `form:"metric,omitempty" json:"metric,omitempty"`
}

// GetPortfolioMetricsParamsWindow defines parameters for GetPortfolioMetrics.
type GetPortfolioMetricsParamsWindow string

// GetPortfolioMetricsParamsMetric defines parameters for GetPortfolioMetrics.
type GetPortfolioMetricsParamsMetric string

// GetPortfolioPerformanceParams defines parameters for GetPortfolioPerformance.
type GetPortfolioPerformanceParams struct {
	// From ISO date (YYYY-MM-DD). Inclusive.
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To ISO date (YYYY-MM-DD). Inclusive.
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// Resolution Downsample target. `daily` (default) or `weekly`/`monthly` for coarser series.
	Resolution *GetPortfolioPerformanceParamsResolution `form:"resolution,omitempty" json:"resolution,omitempty"`
}

// GetPortfolioPerformanceParamsResolution defines parameters for GetPortfolioPerformance.
type GetPortfolioPerformanceParamsResolution string

// GetPortfolioTransactionsParams defines parameters for GetPortfolioTransactions.
type GetPortfolioTransactionsParams struct {
	// From Inclusive start date (YYYY-MM-DD).
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive end date (YYYY-MM-DD).
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// Type Comma-separated list of transaction types to include.
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// DescribeStrategyParams defines parameters for DescribeStrategy.
type DescribeStrategyParams struct {
	// CloneUrl HTTPS GitHub clone URL.
	CloneUrl string `form:"cloneUrl" json:"cloneUrl"`
}

// CreatePortfolioJSONRequestBody defines body for CreatePortfolio for application/json ContentType.
type CreatePortfolioJSONRequestBody = PortfolioCreateRequest

// UpdatePortfolioJSONRequestBody defines body for UpdatePortfolio for application/json ContentType.
type UpdatePortfolioJSONRequestBody = PortfolioUpdateRequest

// CreatePortfolioAlertJSONRequestBody defines body for CreatePortfolioAlert for application/json ContentType.
type CreatePortfolioAlertJSONRequestBody = AlertCreateRequest

// UpdatePortfolioAlertJSONRequestBody defines body for UpdatePortfolioAlert for application/json ContentType.
type UpdatePortfolioAlertJSONRequestBody = AlertUpdateRequest
