// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for MetricFormat.
const (
	Number  MetricFormat = "number"
	Percent MetricFormat = "percent"
)

// Valid indicates whether the value is a known member of the MetricFormat enum.
func (e MetricFormat) Valid() bool {
	switch e {
	case Number:
		return true
	case Percent:
		return true
	default:
		return false
	}
}

// Defines values for PortfolioMeasurementsResolution.
const (
	PortfolioMeasurementsResolutionDaily   PortfolioMeasurementsResolution = "daily"
	PortfolioMeasurementsResolutionMonthly PortfolioMeasurementsResolution = "monthly"
	PortfolioMeasurementsResolutionWeekly  PortfolioMeasurementsResolution = "weekly"
)

// Valid indicates whether the value is a known member of the PortfolioMeasurementsResolution enum.
func (e PortfolioMeasurementsResolution) Valid() bool {
	switch e {
	case PortfolioMeasurementsResolutionDaily:
		return true
	case PortfolioMeasurementsResolutionMonthly:
		return true
	case PortfolioMeasurementsResolutionWeekly:
		return true
	default:
		return false
	}
}

// Defines values for PortfolioMode.
const (
	Continuous PortfolioMode = "continuous"
	OneShot    PortfolioMode = "one_shot"
)

// Valid indicates whether the value is a known member of the PortfolioMode enum.
func (e PortfolioMode) Valid() bool {
	switch e {
	case Continuous:
		return true
	case OneShot:
		return true
	default:
		return false
	}
}

// Defines values for ReturnRowKind.
const (
	ReturnRowKindBenchmark    ReturnRowKind = "benchmark"
	ReturnRowKindBenchmarkTax ReturnRowKind = "benchmark-tax"
	ReturnRowKindPortfolio    ReturnRowKind = "portfolio"
	ReturnRowKindPortfolioTax ReturnRowKind = "portfolio-tax"
)

// Valid indicates whether the value is a known member of the ReturnRowKind enum.
func (e ReturnRowKind) Valid() bool {
	switch e {
	case ReturnRowKindBenchmark:
		return true
	case ReturnRowKindBenchmarkTax:
		return true
	case ReturnRowKindPortfolio:
		return true
	case ReturnRowKindPortfolioTax:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusFailed  RunStatus = "failed"
	RunStatusQueued  RunStatus = "queued"
	RunStatusRunning RunStatus = "running"
	RunStatusSuccess RunStatus = "success"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusFailed:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for StrategyInstallState.
const (
	StrategyInstallStateFailed     StrategyInstallState = "failed"
	StrategyInstallStateInstalling StrategyInstallState = "installing"
	StrategyInstallStatePending    StrategyInstallState = "pending"
	StrategyInstallStateReady      StrategyInstallState = "ready"
)

// Valid indicates whether the value is a known member of the StrategyInstallState enum.
func (e StrategyInstallState) Valid() bool {
	switch e {
	case StrategyInstallStateFailed:
		return true
	case StrategyInstallStateInstalling:
		return true
	case StrategyInstallStatePending:
		return true
	case StrategyInstallStateReady:
		return true
	default:
		return false
	}
}

// Defines values for GetPortfolioMeasurementsParamsResolution.
const (
	GetPortfolioMeasurementsParamsResolutionDaily   GetPortfolioMeasurementsParamsResolution = "daily"
	GetPortfolioMeasurementsParamsResolutionMonthly GetPortfolioMeasurementsParamsResolution = "monthly"
	GetPortfolioMeasurementsParamsResolutionWeekly  GetPortfolioMeasurementsParamsResolution = "weekly"
)

// Valid indicates whether the value is a known member of the GetPortfolioMeasurementsParamsResolution enum.
func (e GetPortfolioMeasurementsParamsResolution) Valid() bool {
	switch e {
	case GetPortfolioMeasurementsParamsResolutionDaily:
		return true
	case GetPortfolioMeasurementsParamsResolutionMonthly:
		return true
	case GetPortfolioMeasurementsParamsResolutionWeekly:
		return true
	default:
		return false
	}
}

// Defines values for ListStrategiesParamsInclude.
const (
	Unofficial ListStrategiesParamsInclude = "unofficial"
)

// Valid indicates whether the value is a known member of the ListStrategiesParamsInclude enum.
func (e ListStrategiesParamsInclude) Valid() bool {
	switch e {
	case Unofficial:
		return true
	default:
		return false
	}
}

// AllocationRow defines model for AllocationRow.
type AllocationRow struct {
	// DayChange Decimal percent since previous close.
	DayChange *float64 `json:"dayChange,omitempty"`
	Name      string   `json:"name"`
	Ticker    string   `json:"ticker"`

	// Value Current market value in USD.
	Value *float64 `json:"value,omitempty"`

	// Weight Fraction of portfolio (0.58 = 58%).
	Weight float64 `json:"weight"`
}

// BacktestRun defines model for BacktestRun.
type BacktestRun struct {
	DurationMs    *int               `json:"durationMs,omitempty"`
	Error         *string            `json:"error,omitempty"`
	FinishedAt    *time.Time         `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	PortfolioSlug string             `json:"portfolioSlug"`
	StartedAt     *time.Time         `json:"startedAt,omitempty"`
	Status        RunStatus          `json:"status"`
}

// Drawdown defines model for Drawdown.
type Drawdown struct {
	// Days Trading days from start to recovery (or end of series if unrecovered).
	Days *int `json:"days,omitempty"`

	// Depth Decimal percent, negative (e.g. -0.1670 = −16.70%).
	Depth float64 `json:"depth"`

	// Recovery Date equity returned to the prior peak. Null if unrecovered.
	Recovery *openapi_types.Date `json:"recovery,omitempty"`

	// Start Peak date when the drawdown began.
	Start openapi_types.Date `json:"start"`

	// Trough Date of the deepest point.
	Trough openapi_types.Date `json:"trough"`
}

// MeasurementPoint defines model for MeasurementPoint.
type MeasurementPoint struct {
	// BenchmarkValue Normalized to start at the portfolio's opening value.
	BenchmarkValue float64            `json:"benchmarkValue"`
	Date           openapi_types.Date `json:"date"`
	PortfolioValue float64            `json:"portfolioValue"`

	// RiskFreeRate Annualized risk-free rate at this date (e.g. 3-month T-Bill). Optional.
	RiskFreeRate *float64 `json:"riskFreeRate,omitempty"`
}

// MetricFormat How the value should be rendered. Percent values are decimal (0.1147 = 11.47%).
type MetricFormat string

// Portfolio defines model for Portfolio.
type Portfolio struct {
	// Allocation Current holdings with weight (sum ≈ 1.0).
	Allocation []AllocationRow `json:"allocation"`

	// Benchmark Benchmark label, e.g. `S&P 500 TR`.
	Benchmark string `json:"benchmark"`

	// CurrentAssets Tickers currently held (excluding cash).
	CurrentAssets []string `json:"currentAssets"`

	// Drawdowns Ordered by depth (deepest first).
	Drawdowns     []Drawdown         `json:"drawdowns"`
	Id            openapi_types.UUID `json:"id"`
	InceptionDate openapi_types.Date `json:"inceptionDate"`
	LastUpdated   time.Time          `json:"lastUpdated"`

	// Metrics Trailing statistics for the Risk & style metrics panel.
	Metrics []PortfolioMetric `json:"metrics"`
	Name    string            `json:"name"`

	// Summary Top-line numbers for the KPI strip.
	Summary PortfolioSummary `json:"summary"`

	// TrailingReturns Rows for the trailing returns table.
	TrailingReturns []TrailingReturnRow `json:"trailingReturns"`
}

// PortfolioCreateRequest defines model for PortfolioCreateRequest.
type PortfolioCreateRequest struct {
	Benchmark *string       `json:"benchmark,omitempty"`
	Mode      PortfolioMode `json:"mode"`

	// Name User-visible display name.
	Name string `json:"name"`

	// Parameters Values validated against the strategy's declared parameters.
	Parameters map[string]interface{} `json:"parameters"`

	// RunNow If true, kick the first run immediately after create.
	RunNow *bool `json:"runNow,omitempty"`

	// Schedule tradecron string, required iff mode=continuous (e.g. `@monthend`).
	Schedule *string `json:"schedule,omitempty"`

	// StrategyCode Strategy short code (from `describe` output).
	StrategyCode string `json:"strategyCode"`

	// StrategyVer Specific version to pin; omit for latest installed.
	StrategyVer *string `json:"strategyVer,omitempty"`
}

// PortfolioListItem Light metadata for the dashboard/list view.
type PortfolioListItem struct {
	Benchmark     string             `json:"benchmark"`
	CurrentValue  float64            `json:"currentValue"`
	Id            openapi_types.UUID `json:"id"`
	InceptionDate openapi_types.Date `json:"inceptionDate"`
	LastUpdated   time.Time          `json:"lastUpdated"`

	// MaxDrawDown Decimal percent, negative.
	MaxDrawDown float64 `json:"maxDrawDown"`
	Name        string  `json:"name"`

	// YtdReturn Decimal percent (0.0714 = 7.14%).
	YtdReturn float64 `json:"ytdReturn"`
}

// PortfolioMeasurements defines model for PortfolioMeasurements.
type PortfolioMeasurements struct {
	From          openapi_types.Date               `json:"from"`
	Points        []MeasurementPoint               `json:"points"`
	PortfolioSlug string                           `json:"portfolioSlug"`
	Resolution    *PortfolioMeasurementsResolution `json:"resolution,omitempty"`
	To            openapi_types.Date               `json:"to"`
}

// PortfolioMeasurementsResolution defines model for PortfolioMeasurements.Resolution.
type PortfolioMeasurementsResolution string

// PortfolioMetric defines model for PortfolioMetric.
type PortfolioMetric struct {
	// Format How the value should be rendered. Percent values are decimal (0.1147 = 11.47%).
	Format MetricFormat `json:"format"`
	Label  string       `json:"label"`
	Value  float64      `json:"value"`
}

// PortfolioMode defines model for PortfolioMode.
type PortfolioMode string

// PortfolioSummary Top-line numbers for the KPI strip.
type PortfolioSummary struct {
	Alpha              float64  `json:"alpha"`
	Beta               float64  `json:"beta"`
	CagrSinceInception float64  `json:"cagrSinceInception"`
	CurrentValue       float64  `json:"currentValue"`
	MaxDrawDown        float64  `json:"maxDrawDown"`
	OneYearReturn      float64  `json:"oneYearReturn"`
	Sharpe             float64  `json:"sharpe"`
	Sortino            float64  `json:"sortino"`
	StdDev             float64  `json:"stdDev"`
	TaxCostRatio       float64  `json:"taxCostRatio"`
	UlcerIndex         *float64 `json:"ulcerIndex,omitempty"`
	YtdReturn          float64  `json:"ytdReturn"`
}

// PortfolioUpdateRequest All fields optional; only provided fields are updated.
type PortfolioUpdateRequest struct {
	Name       *string                 `json:"name,omitempty"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Schedule   *string                 `json:"schedule,omitempty"`
}

// Problem RFC 7807 Problem Details.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference that identifies the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title Short, human-readable summary.
	Title string `json:"title"`

	// Type URI identifying the problem type.
	Type *string `json:"type,omitempty"`
}

// ReturnRowKind Which line in the trailing returns table.
type ReturnRowKind string

// RunStatus defines model for RunStatus.
type RunStatus string

// Strategy defines model for Strategy.
type Strategy struct {
	Cagr             *float64             `json:"cagr,omitempty"`
	Categories       *[]string            `json:"categories,omitempty"`
	CloneUrl         *string              `json:"cloneUrl,omitempty"`
	Describe         *StrategyDescribe    `json:"describe,omitempty"`
	Description      *string              `json:"description,omitempty"`
	InstallError     *string              `json:"installError,omitempty"`
	InstallState     StrategyInstallState `json:"installState"`
	InstalledAt      *time.Time           `json:"installedAt,omitempty"`
	InstalledVer     *string              `json:"installedVer,omitempty"`
	IsOfficial       bool                 `json:"isOfficial"`
	LastAttemptedVer *string              `json:"lastAttemptedVer,omitempty"`
	MaxDrawDown      *float64             `json:"maxDrawDown,omitempty"`

	// OwnerSub Auth0 sub of the registering user; NULL for official strategies.
	OwnerSub  *string  `json:"ownerSub,omitempty"`
	RepoName  string   `json:"repoName"`
	RepoOwner string   `json:"repoOwner"`
	Sharpe    *float64 `json:"sharpe,omitempty"`
	ShortCode string   `json:"shortCode"`
	Stars     *int     `json:"stars,omitempty"`
}

// StrategyInstallState defines model for Strategy.InstallState.
type StrategyInstallState string

// StrategyDescribe defines model for StrategyDescribe.
type StrategyDescribe struct {
	Benchmark   string              `json:"benchmark"`
	Description *string             `json:"description,omitempty"`
	Name        string              `json:"name"`
	Parameters  []StrategyParameter `json:"parameters"`
	Presets     *[]StrategyPreset   `json:"presets,omitempty"`
	Schedule    string              `json:"schedule"`
	ShortCode   string              `json:"shortCode"`
}

// StrategyParameter defines model for StrategyParameter.
type StrategyParameter struct {
	// Default Default value — may be any JSON-serializable type.
	Default     interface{} `json:"default,omitempty"`
	Description *string     `json:"description,omitempty"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
}

// StrategyPreset defines model for StrategyPreset.
type StrategyPreset struct {
	Name       string                 `json:"name"`
	Parameters map[string]interface{} `json:"parameters"`
}

// StrategyRegisterRequest defines model for StrategyRegisterRequest.
type StrategyRegisterRequest struct {
	// CloneUrl HTTPS clone URL for the strategy repository.
	CloneUrl string `json:"cloneUrl"`
}

// TrailingReturnRow defines model for TrailingReturnRow.
type TrailingReturnRow struct {
	FiveYear float64 `json:"fiveYear"`

	// Kind Which line in the trailing returns table.
	Kind           ReturnRowKind `json:"kind"`
	OneYear        float64       `json:"oneYear"`
	SinceInception float64       `json:"sinceInception"`
	TenYear        float64       `json:"tenYear"`
	ThreeYear      float64       `json:"threeYear"`
	Title          string        `json:"title"`
	Ytd            float64       `json:"ytd"`
}

// PortfolioSlug defines model for PortfolioSlug.
type PortfolioSlug = string

// Conflict RFC 7807 Problem Details.
type Conflict = Problem

// NotFound RFC 7807 Problem Details.
type NotFound = Problem

// ServerError RFC 7807 Problem Details.
type ServerError = Problem

// Unauthorized RFC 7807 Problem Details.
type Unauthorized = Problem

// UnprocessableEntity RFC 7807 Problem Details.
type UnprocessableEntity = Problem

// GetPortfolioMeasurementsParams defines parameters for GetPortfolioMeasurements.
type GetPortfolioMeasurementsParams struct {
	// From ISO date (YYYY-MM-DD). Inclusive.
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To ISO date (YYYY-MM-DD). Inclusive.
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// Resolution Downsample target. `daily` (default) or `weekly`/`monthly` for coarser series.
	Resolution *GetPortfolioMeasurementsParamsResolution `form:"resolution,omitempty" json:"resolution,omitempty"`
}

// GetPortfolioMeasurementsParamsResolution defines parameters for GetPortfolioMeasurements.
type GetPortfolioMeasurementsParamsResolution string

// ListStrategiesParams defines parameters for ListStrategies.
type ListStrategiesParams struct {
	// Include Set to `unofficial` to include the caller's registered unofficial strategies.
	Include *ListStrategiesParamsInclude `form:"include,omitempty" json:"include,omitempty"`
}

// ListStrategiesParamsInclude defines parameters for ListStrategies.
type ListStrategiesParamsInclude string

// CreatePortfolioJSONRequestBody defines body for CreatePortfolio for application/json ContentType.
type CreatePortfolioJSONRequestBody = PortfolioCreateRequest

// UpdatePortfolioJSONRequestBody defines body for UpdatePortfolio for application/json ContentType.
type UpdatePortfolioJSONRequestBody = PortfolioUpdateRequest

// RegisterUnofficialStrategyJSONRequestBody defines body for RegisterUnofficialStrategy for application/json ContentType.
type RegisterUnofficialStrategyJSONRequestBody = StrategyRegisterRequest
