[[category]]
name = "Income:Dividends"
primary = "INCOME"
secondary = "INCOME_DIVIDENDS"
description = "Dividends from investment accounts"

[[category]]
name = "Income:Interest Earned"
primary = "INCOME"
secondary = "INCOME_INTEREST_EARNED"
description = "Income from interest on savings accounts"

[[category]]
name = "Income:Retirement Pension"
primary = "INCOME"
secondary = "INCOME_RETIREMENT_PENSION"
description = "Income from pension payments"

[[category]]
name = "Income:Tax Refund"
primary = "INCOME"
secondary = "INCOME_TAX_REFUND"
description = "Income from tax refunds"

[[category]]
name = "Income:Unemployment"
primary = "INCOME"
secondary = "INCOME_UNEMPLOYMENT"
description = "Income from unemployment benefits, including unemployment insurance and healthcare"

[[category]]
name = "Income:Wages"
primary = "INCOME"
secondary = "INCOME_WAGES"
description = "Income from salaries, gig-economy work, and tips earned"

[[category]]
name = "Income:Other Income"
primary = "INCOME"
secondary = "INCOME_OTHER_INCOME"
description = "Other miscellaneous income, including alimony, social security, child support, and rental"

[[category]]
name = "Transfer In:Cash Advances and Loans"
primary = "TRANSFER_IN"
secondary = "TRANSFER_IN_CASH_ADVANCES_AND_LOANS"
description = "Loans and cash advances deposited into a bank account"

[[category]]
name = "Transfer In:Deposit"
primary = "TRANSFER_IN"
secondary = "TRANSFER_IN_DEPOSIT"
description = "Cash, checks, and ATM deposits into a bank account"

[[category]]
name = "Transfer In:Investment and Retirement Funds"
primary = "TRANSFER_IN"
secondary = "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS"
description = "Inbound transfers to an investment or retirement account"

[[category]]
name = "Transfer In:Savings"
primary = "TRANSFER_IN"
secondary = "TRANSFER_IN_SAVINGS"
description = "Inbound transfers to a savings account"

[[category]]
name = "Transfer In:Account Transfer"
primary = "TRANSFER_IN"
secondary = "TRANSFER_IN_ACCOUNT_TRANSFER"
description = "General inbound transfers from another account"

[[category]]
name = "Transfer In:Other Transfer In"
primary = "TRANSFER_IN"
secondary = "TRANSFER_IN_OTHER_TRANSFER_IN"
description = "Other miscellaneous inbound transactions"

[[category]]
name = "Transfer Out:Investment and Retirement Funds"
primary = "TRANSFER_OUT"
secondary = "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS"
description = "Transfers to an investment or retirement account, including investment apps such as Acorns, Betterment"

[[category]]
name = "Transfer Out:Savings"
primary = "TRANSFER_OUT"
secondary = "TRANSFER_OUT_SAVINGS"
description = "Outbound transfers to savings accounts"

[[category]]
name = "Transfer Out:Withdrawal"
primary = "TRANSFER_OUT"
secondary = "TRANSFER_OUT_WITHDRAWAL"
description = "Withdrawals from a bank account"

[[category]]
name = "Transfer Out:Account Transfer"
primary = "TRANSFER_OUT"
secondary = "TRANSFER_OUT_ACCOUNT_TRANSFER"
description = "General outbound transfers to another account"

[[category]]
name = "Transfer Out:Other Transfer Out"
primary = "TRANSFER_OUT"
secondary = "TRANSFER_OUT_OTHER_TRANSFER_OUT"
description = "Other miscellaneous outbound transactions"

[[category]]
name = "Loan Payments:Car Payment"
primary = "LOAN_PAYMENTS"
secondary = "LOAN_PAYMENTS_CAR_PAYMENT"
description = "Car loans and leases"

[[category]]
name = "Loan Payments:Credit Card Payment"
primary = "LOAN_PAYMENTS"
secondary = "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT"
description = "Payments to a credit card. These are positive amounts for credit card subtypes and negative for depository subtypes"

[[category]]
name = "Loan Payments:Personal Loan Payment"
primary = "LOAN_PAYMENTS"
secondary = "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT"
description = "Personal loans, including cash advances and buy now pay later repayments"

[[category]]
name = "Loan Payments:Mortgage Payment"
primary = "LOAN_PAYMENTS"
secondary = "LOAN_PAYMENTS_MORTGAGE_PAYMENT"
description = "Payments on mortgages"

[[category]]
name = "Loan Payments:Student Loan Payment"
primary = "LOAN_PAYMENTS"
secondary = "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT"
description = "Payments on student loans. For college tuition, refer to 'General Services - Education'"

[[category]]
name = "Loan Payments:Other Payment"
primary = "LOAN_PAYMENTS"
secondary = "LOAN_PAYMENTS_OTHER_PAYMENT"
description = "Other miscellaneous debt payments"

[[category]]
name = "Bank Fees:ATM Fees"
primary = "BANK_FEES"
secondary = "BANK_FEES_ATM_FEES"
description = "Fees incurred for out-of-network ATMs"

[[category]]
name = "Bank Fees:Foreign Transaction Fees"
primary = "BANK_FEES"
secondary = "BANK_FEES_FOREIGN_TRANSACTION_FEES"
description = "Fees incurred on non-domestic transactions"

[[category]]
name = "Bank Fees:Insufficient Funds"
primary = "BANK_FEES"
secondary = "BANK_FEES_INSUFFICIENT_FUNDS"
description = "Fees relating to insufficient funds"

[[category]]
name = "Bank Fees:Interest Charge"
primary = "BANK_FEES"
secondary = "BANK_FEES_INTEREST_CHARGE"
description = "Fees incurred for interest on purchases, including not-paid-in-full or interest on cash advances"

[[category]]
name = "Bank Fees:Overdraft Fees"
primary = "BANK_FEES"
secondary = "BANK_FEES_OVERDRAFT_FEES"
description = "Fees incurred when an account is in overdraft"

[[category]]
name = "Bank Fees:Other Bank Fees"
primary = "BANK_FEES"
secondary = "BANK_FEES_OTHER_BANK_FEES"
description = "Other miscellaneous bank fees"

[[category]]
name = "Entertainment:Casinos and Gambling"
primary = "ENTERTAINMENT"
secondary = "ENTERTAINMENT_CASINOS_AND_GAMBLING"
description = "Gambling, casinos, and sports betting"

[[category]]
name = "Entertainment:Music and Audio"
primary = "ENTERTAINMENT"
secondary = "ENTERTAINMENT_MUSIC_AND_AUDIO"
description = "Digital and in-person music purchases, including music streaming services"

[[category]]
name = "Entertainment:Sporting Events, Amusement Parks, and Museums"
primary = "ENTERTAINMENT"
secondary = "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS"
description = "Purchases made at sporting events, music venues, concerts, museums, and amusement parks"

[[category]]
name = "Entertainment:TV and Movies"
primary = "ENTERTAINMENT"
secondary = "ENTERTAINMENT_TV_AND_MOVIES"
description = "In home movie streaming services and movie theaters"

[[category]]
name = "Entertainment:Video Games"
primary = "ENTERTAINMENT"
secondary = "ENTERTAINMENT_VIDEO_GAMES"
description = "Digital and in-person video game purchases"

[[category]]
name = "Entertainment:Other Entertainment"
primary = "ENTERTAINMENT"
secondary = "ENTERTAINMENT_OTHER_ENTERTAINMENT"
description = "Other miscellaneous entertainment purchases, including night life and adult entertainment"

[[category]]
name = "Food and Drink:Beer, Wine, and Liquor"
primary = "FOOD_AND_DRINK"
secondary = "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR"
description = "Beer, Wine & Liquor Stores"

[[category]]
name = "Food and Drink:Coffee"
primary = "FOOD_AND_DRINK"
secondary = "FOOD_AND_DRINK_COFFEE"
description = "Purchases at coffee shops or cafes"

[[category]]
name = "Food and Drink:Fast Food"
primary = "FOOD_AND_DRINK"
secondary = "FOOD_AND_DRINK_FAST_FOOD"
description = "Dining expenses for fast food chains"

[[category]]
name = "Food and Drink:Groceries"
primary = "FOOD_AND_DRINK"
secondary = "FOOD_AND_DRINK_GROCERIES"
description = "Purchases for fresh produce and groceries, including farmers' markets"

[[category]]
name = "Food and Drink:Restaurant"
primary = "FOOD_AND_DRINK"
secondary = "FOOD_AND_DRINK_RESTAURANT"
description = "Dining expenses for restaurants, bars, gastropubs, and diners"

[[category]]
name = "Food and Drink:Vending Machines"
primary = "FOOD_AND_DRINK"
secondary = "FOOD_AND_DRINK_VENDING_MACHINES"
description = "Purchases made at vending machine operators"

[[category]]
name = "Food and Drink:Other Food and Drink"
primary = "FOOD_AND_DRINK"
secondary = "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK"
description = "Other miscellaneous food and drink, including desserts, juice bars, and delis"

[[category]]
name = "General Merchandise:Bookstores and Newstands"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS"
description = "Books, magazines, and news "

[[category]]
name = "General Merchandise:Clothing and Accessories"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES"
description = "Apparel, shoes, and jewelry"

[[category]]
name = "General Merchandise:Convenience Stores"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_CONVENIENCE_STORES"
description = "Purchases at convenience stores"

[[category]]
name = "General Merchandise:Department Stores"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_DEPARTMENT_STORES"
description = "Retail stores with wide ranges of consumer goods, typically specializing in clothing and home goods"

[[category]]
name = "General Merchandise:Discount Stores"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_DISCOUNT_STORES"
description = "Stores selling goods at a discounted price"

[[category]]
name = "General Merchandise:Electronics"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_ELECTRONICS"
description = "Electronics stores and websites"

[[category]]
name = "General Merchandise:Gifts and Novelties"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES"
description = "Photo, gifts, cards, and floral stores"

[[category]]
name = "General Merchandise:Office Supplies"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_OFFICE_SUPPLIES"
description = "Stores that specialize in office goods"

[[category]]
name = "General Merchandise:Online Marketplaces"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES"
description = "Multi-purpose e-commerce platforms such as Etsy, Ebay and Amazon"

[[category]]
name = "General Merchandise:Pet Supplies"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_PET_SUPPLIES"
description = "Pet supplies and pet food"

[[category]]
name = "General Merchandise:Sporting Goods"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_SPORTING_GOODS"
description = "Sporting goods, camping gear, and outdoor equipment"

[[category]]
name = "General Merchandise:Superstores"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_SUPERSTORES"
description = "Superstores such as Target and Walmart, selling both groceries and general merchandise"

[[category]]
name = "General Merchandise:Tobacco and Vape"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE"
description = "Purchases for tobacco and vaping products"

[[category]]
name = "General Merchandise:Other General Merchandise"
primary = "GENERAL_MERCHANDISE"
secondary = "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE"
description = "Other miscellaneous merchandise, including toys, hobbies, and arts and crafts"

[[category]]
name = "Home Improvement:Furniture"
primary = "HOME_IMPROVEMENT"
secondary = "HOME_IMPROVEMENT_FURNITURE"
description = "Furniture, bedding, and home accessories"

[[category]]
name = "Home Improvement:Hardware"
primary = "HOME_IMPROVEMENT"
secondary = "HOME_IMPROVEMENT_HARDWARE"
description = "Building materials, hardware stores, paint, and wallpaper"

[[category]]
name = "Home Improvement:Repair and Maintenance"
primary = "HOME_IMPROVEMENT"
secondary = "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE"
description = "Plumbing, lighting, gardening, and roofing"

[[category]]
name = "Home Improvement:Security"
primary = "HOME_IMPROVEMENT"
secondary = "HOME_IMPROVEMENT_SECURITY"
description = "Home security system purchases"

[[category]]
name = "Home Improvement:Other Home Improvement"
primary = "HOME_IMPROVEMENT"
secondary = "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT"
description = "Other miscellaneous home purchases, including pool installation and pest control"

[[category]]
name = "Medical:Dental Care"
primary = "MEDICAL"
secondary = "MEDICAL_DENTAL_CARE"
description = "Dentists and general dental care"

[[category]]
name = "Medical:Eye Care"
primary = "MEDICAL"
secondary = "MEDICAL_EYE_CARE"
description = "Optometrists, contacts, and glasses stores"

[[category]]
name = "Medical:Nursing Care"
primary = "MEDICAL"
secondary = "MEDICAL_NURSING_CARE"
description = "Nursing care and facilities"

[[category]]
name = "Medical:Pharmacies and Supplements"
primary = "MEDICAL"
secondary = "MEDICAL_PHARMACIES_AND_SUPPLEMENTS"
description = "Pharmacies and nutrition shops"

[[category]]
name = "Medical:Primary Care"
primary = "MEDICAL"
secondary = "MEDICAL_PRIMARY_CARE"
description = "Doctors and physicians"

[[category]]
name = "Medical:Veterinary Services"
primary = "MEDICAL"
secondary = "MEDICAL_VETERINARY_SERVICES"
description = "Prevention and care procedures for animals"

[[category]]
name = "Medical:Other Medical"
primary = "MEDICAL"
secondary = "MEDICAL_OTHER_MEDICAL"
description = "Other miscellaneous medical, including blood work, hospitals, and ambulances"

[[category]]
name = "Personal Care:Gyms and Fitness Centers"
primary = "PERSONAL_CARE"
secondary = "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS"
description = "Gyms, fitness centers, and workout classes"

[[category]]
name = "Personal Care:Hair and Beauty"
primary = "PERSONAL_CARE"
secondary = "PERSONAL_CARE_HAIR_AND_BEAUTY"
description = "Manicures, haircuts, waxing, spa/massages, and bath and beauty products"

[[category]]
name = "Personal Care:Laundry and Dry Cleaning"
primary = "PERSONAL_CARE"
secondary = "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING"
description = "Wash and fold, and dry cleaning expenses"

[[category]]
name = "Personal Care:Other Personal Care"
primary = "PERSONAL_CARE"
secondary = "PERSONAL_CARE_OTHER_PERSONAL_CARE"
description = "Other miscellaneous personal care, including mental health apps and services"

[[category]]
name = "General Services:Accounting and Financial Planning"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING"
description = "Financial planning, and tax and accounting services"

[[category]]
name = "General Services:Automotive"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_AUTOMOTIVE"
description = "Oil changes, car washes, repairs, and towing"

[[category]]
name = "General Services:Childcare"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_CHILDCARE"
description = "Babysitters and daycare"

[[category]]
name = "General Services:Consulting and Legal"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_CONSULTING_AND_LEGAL"
description = "Consulting and legal services"

[[category]]
name = "General Services:Education"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_EDUCATION"
description = "Elementary, high school, professional schools, and college tuition"

[[category]]
name = "General Services:Insurance"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_INSURANCE"
description = "Insurance for auto, home, and healthcare"

[[category]]
name = "General Services:Postage and Shipping"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_POSTAGE_AND_SHIPPING"
description = "Mail, packaging, and shipping services"

[[category]]
name = "General Services:Storage"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_STORAGE"
description = "Storage services and facilities"

[[category]]
name = "General Services:Other General Services"
primary = "GENERAL_SERVICES"
secondary = "GENERAL_SERVICES_OTHER_GENERAL_SERVICES"
description = "Other miscellaneous services, including advertising and cloud storage"

[[category]]
name = "Government and Non-Profit:Donations"
primary = "GOVERNMENT_AND_NON_PROFIT"
secondary = "GOVERNMENT_AND_NON_PROFIT_DONATIONS"
description = "Charitable, political, and religious donations"

[[category]]
name = "Government and Non-Profit:Goverment Departments and Agencies"
primary = "GOVERNMENT_AND_NON_PROFIT"
secondary = "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES"
description = "Government departments and agencies, such as driving licences, and passport renewal"

[[category]]
name = "Government and Non-Profit:Tax Payment"
primary = "GOVERNMENT_AND_NON_PROFIT"
secondary = "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT"
description = "Tax payments, including income and property taxes"

[[category]]
name = "Government and Non-Profit:Other Government and Non-Profit"
primary = "GOVERNMENT_AND_NON_PROFIT"
secondary = "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT"
description = "Other miscellaneous government and non-profit agencies"

[[category]]
name = "Transportation:Bikes and Scooters"
primary = "TRANSPORTATION"
secondary = "TRANSPORTATION_BIKES_AND_SCOOTERS"
description = "Bike and scooter rentals"

[[category]]
name = "Transportation:Gas"
primary = "TRANSPORTATION"
secondary = "TRANSPORTATION_GAS"
description = "Purchases at a gas station"

[[category]]
name = "Transportation:Parking"
primary = "TRANSPORTATION"
secondary = "TRANSPORTATION_PARKING"
description = "Parking fees and expenses"

[[category]]
name = "Transportation:Public Transit"
primary = "TRANSPORTATION"
secondary = "TRANSPORTATION_PUBLIC_TRANSIT"
description = "Public transportation, including rail and train, buses, and metro"

[[category]]
name = "Transportation:Taxis and Ride Shares"
primary = "TRANSPORTATION"
secondary = "TRANSPORTATION_TAXIS_AND_RIDE_SHARES"
description = "Taxi and ride share services"

[[category]]
name = "Transportation:Tolls"
primary = "TRANSPORTATION"
secondary = "TRANSPORTATION_TOLLS"
description = "Toll expenses"

[[category]]
name = "Transportation:Other Transportation"
primary = "TRANSPORTATION"
secondary = "TRANSPORTATION_OTHER_TRANSPORTATION"
description = "Other miscellaneous transportation expenses"

[[category]]
name = "Travel:Flights"
primary = "TRAVEL"
secondary = "TRAVEL_FLIGHTS"
description = "Airline expenses"

[[category]]
name = "Travel:Lodging"
primary = "TRAVEL"
secondary = "TRAVEL_LODGING"
description = "Hotels, motels, and hosted accommodation such as Airbnb"

[[category]]
name = "Travel:Rental Cars"
primary = "TRAVEL"
secondary = "TRAVEL_RENTAL_CARS"
description = "Rental cars, charter buses, and trucks"

[[category]]
name = "Travel:Other Travel"
primary = "TRAVEL"
secondary = "TRAVEL_OTHER_TRAVEL"
description = "Other miscellaneous travel expenses"

[[category]]
name = "Rent and Utilities:Gas and Electricity"
primary = "RENT_AND_UTILITIES"
secondary = "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY"
description = "Gas and electricity bills"

[[category]]
name = "Rent and Utilities:Internet and Cable"
primary = "RENT_AND_UTILITIES"
secondary = "RENT_AND_UTILITIES_INTERNET_AND_CABLE"
description = "Internet and cable bills"

[[category]]
name = "Rent and Utilities:Rent"
primary = "RENT_AND_UTILITIES"
secondary = "RENT_AND_UTILITIES_RENT"
description = "Rent payment"

[[category]]
name = "Rent and Utilities:Sewage and Waste Management"
primary = "RENT_AND_UTILITIES"
secondary = "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT"
description = "Sewage and garbage disposal bills"

[[category]]
name = "Rent and Utilities:Telephone"
primary = "RENT_AND_UTILITIES"
secondary = "RENT_AND_UTILITIES_TELEPHONE"
description = "Cell phone bills"

[[category]]
name = "Rent and Utilities:Water"
primary = "RENT_AND_UTILITIES"
secondary = "RENT_AND_UTILITIES_WATER"
description = "Water bills"

[[category]]
name = "Rent and Utilities:Other Utilities"
primary = "RENT_AND_UTILITIES"
secondary = "RENT_AND_UTILITIES_OTHER_UTILITIES"
description = "Other miscellaneous utility bills"
