name: CI
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PGHOST: localhost
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Add PostgreSQL binaries to PATH
        shell: bash
        run: |
            echo "$(pg_config --bindir)" >> $GITHUB_PATH
      - name: Start preinstalled PostgreSQL
        shell: bash
        run: |
          echo "Initializing database cluster..."

          export PGHOST="${RUNNER_TEMP}/postgres"
          export PGDATA="$PGHOST/pgdata"
          mkdir -p "$PGDATA"

          # initdb requires file for password in non-interactive mode
          export PWFILE="$RUNNER_TEMP/pwfile"
          echo "postgres" > "$PWFILE"
          initdb --pgdata="$PGDATA" --username="postgres" --pwfile="$PWFILE"

          echo "Starting PostgreSQL..."
          echo "unix_socket_directories = '$PGHOST'" >> "$PGDATA/postgresql.conf"
          pg_ctl start
      - run: go install github.com/onsi/ginkgo/v2/ginkgo@latest && ginkgo run -r --race --junit-report test-report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'test-report.xml'
          check_name: 'Ginkgo Test Report'
      - run: ginkgo run -r --coverprofile=coverage.txt --covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4