name: CI
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        continue-on-error: true
        with:
          version: latest

      - name: Test
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          ginkgo run -r --race --junit-report test-report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: 'test-report.xml'

      - name: Coverage
        run: ginkgo run -r --coverprofile=coverage.txt --covermode=atomic

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
